<<echo=FALSE>>=
library("survival", quietly=TRUE)
opts_chunk$set(comment=NA, tidy=FALSE, highlight=FALSE, echo=FALSE,
               fig.with=7, fig.height=5.5, fig.path="figures/",
               out.width="\\textwidth", out.height="!", device="pdf",
               cache=FALSE, background="#ffffff",
               warning=FALSE, error=FALSE, prompt=TRUE)
options(contrasts= c("contr.treatment", "contr.poly"),
        show.signif.starts = FALSE, continue=" ", width=60)
par(mar=c(4.1, 4.1, 1.1, 1.1))

crisk <- function(what, horizontal = TRUE, ...) {
    nstate <- length(what)
    connect <- matrix(0, nstate, nstate,
                      dimnames=list(what, what))
    connect[1,-1] <- 1  # an arrow from state 1 to each of the others
    if (horizontal) statefig(c(1, nstate-1),  connect, ...)
    else statefig(matrix(c(1, nstate-1), ncol=1), connect, ...)
}
@ 

\section{Competing risk}
\begin{frame}
{\Large Competing risks}
\end{frame}

\begin{frame}{How to model?}
  \begin{itemize}
     \item Model the individual rates $\lambda_{jk}(t)$ from state $j$
     to state $k$
       \begin{itemize}
          \item Separate model for each transition
	  \begin{itemize}
	    \item which covariates for each
	    \item which, if any, coefficients are shared
	    \item what time scale for each transition (baseline hazard)
	    \item do any transitions share a baseline
	    \end{itemize}
	  \item From the set of $\lambda$ functions $p(t)$, lifetime risk,
	  and/or E(time in state) can all be computed
        \end{itemize}
     \item Model $p(t)$ directly (this is harder)
     \item Model E(time in state) or lifetime risk directly. (I don't know of
       a way to do this)
     \end{itemize}
\end{frame}


\begin{frame}{Overview}
<<fourfig>>=
oldpar <- par(mfrow=c(2,2), mar=c(.1, .1, .1, .1))
crisk(c("Alive", "Dead"))
crisk(c("A", "D1", "D2", "D3"))

what <- c("Health", "Illness", "Death")
connect <- matrix(0, 3,3, dimnames=list(what, what))
connect[,3] <- 1
statefig(c(1,2), connect)
delta <- c(-.02, .02)
arrows(c(.35, .65), c(.55, .70) + delta, c(.65, .35), c(.7, .55) + delta,
       angle=20, length= .1)

what <- c("0", "1", "2", "...")
connect <- matrix(0, 4,4, dimnames=list(what, what))
connect[1,2] <- connect[2,3] <- connect[3,4] <- 1
statefig(c(1,1,1,1), connect)
par(oldpar)
@ 
\end{frame}

\begin{frame}{Modeling}
  \begin{enumerate}
  \item Draw the multi-state picture (boxes and arrows). \\
        Tape it on the side of your terminal. \\
        There may be more than one.
  \item Create curves.  Look at them.
  \item Think through the rates (arrows).
    \begin{itemize}
       \item Which covariates should be attached to each rate? 
       \item Which transitions (if any) should have the same coefficients?
       \item Which (if any) should share the same baseline hazard?
       \item Random effects?
    \end{itemize}
  \item Build an appropriate data set.
  \item Fit the rates.
  \end{enumerate}
\end{frame}

\begin{frame}
  \begin{itemize}
    \item A given arrow only depends on the starting box and the transitions
      \begin{itemize}
        \item At risk = in the starting box
        \item Event = transition of \emph{this} type, all others are treated
          as censored
      \end{itemize}
    \item Pr(in state) depends on \emph{all} the transitions.  Curves must
      be fit all at once.
      \begin{itemize}
        \item Nonparametric AJ \code{survfit(Surv(time, outcome) ~ \ldots)}
        \item Cox model: some extra work
      \end{itemize}
  \end{itemize}
\end{frame}

\begin{frame}{Monoclonal Gammopathy of Undetermined Significance (MGUS)}
  \begin{itemize}
    \item Subjects with a dominant clone (2\%) in their plasma cell population,
      but without malignancy.  
    \item Normally found incidentally to other tests.
    \item Should the patient be worried?
      \pause
    \item About 1\% per year convert to overt malignancy.
    \item Essentially independent of age and sex.
    \item Data set \code{mgus2} has information on 1384 subjects.
  \end{itemize}
\end{frame}

\begin{frame}
<<mgus1>>= 
oldpar <- par(mfrow=c(1,2))
hist(mgus2$age, nclass=30, main='', xlab="Age at diagnosis")
#with(mgus2, tapply(age, sex, mean))

mfit1 <- survfit(Surv(futime, death) ~ sex, data=mgus2)
plot(mfit1, col=c(1,2), xscale=12, mark.time=FALSE, lwd=2,
     xlab="Years post diagnosis", ylab="Survival")
legend(200, .8, c("female", "male"), col=1:2, lwd=2, bty='n')
par(oldpar)
@
\end{frame}


\begin{frame}{Competing Risk}
<<mgus2, echo=FALSE>>=
etime <- with(mgus2, ifelse(pstat==0, futime, ptime))
event <- with(mgus2, ifelse(pstat==0, 2*death, 1))
event <- factor(event, 0:2, labels=c("censor", "pcm", "death"))

mfit2 <- survfit(Surv(etime, event) ~ sex, data=mgus2)

oldpar <- par(mar=c(5.1, 4.1, 1,.1))
layout(matrix(1:2,1,2), widths=2:1)
plot(mfit2, col=c(1,2,1,2), lty=c(2,2,1,1),
     mark.time=FALSE, lwd=2,  xscale=12,
     xlab="Years post diagnosis", ylab="Probability in State")
legend(170, .5, c("death w/o PCM:f", "death w/o PCM:m", 
                  "PCM:female", "PCM:male"), 
       col=c(1,2,1,2), lty=c(1,1,2,2), lwd=2, bty='n')

crisk(c("MGUS", "PCM", "Death"))
par(oldpar)
layout(1)
@ 
\end{frame}

\begin{frame}[fragile]
<<mgus2b, echo=TRUE>>=
mfit2 <- survfit(Surv(etime, event) ~ sex, data=mgus2)
print(mfit2, rmean=240, scale=12)

with(mgus2, table(event, sex))
@ 
\end{frame}

\begin{frame}[fragile]
  \frametitle{Event rates}
<<mgu2sb, echo=TRUE>>=
pfit <- pyears(Surv(ptime, pstat) ~ sex, scale=12*100, 
                 data=mgus2)
pfit$event/pfit$pyears
@ 
\begin{itemize}
  \item Overall rate is 1\% per year for males, 1.1\% for females
  \item In 15 years we would expect 15\% to progress
\end{itemize}
\end{frame}

\begin{frame}[fragile]
<<cmugus1, echo=TRUE>>=
cfit1 <- coxph(Surv(ptime, pstat) ~ sex + mspike, mgus2)
round(summary(cfit1)$conf.int, 2)

quantile(mgus2$mspike, na.rm=TRUE)

cfit2 <- coxph(Surv(futime, death) ~ sex + mspike, mgus2)
round(summary(cfit2)$conf.int, 2)
@ 
\end{frame}

\begin{frame}
\begin{itemize}
  \item Sex has no impact on the rate of progression to PCM \\
    but a major impact on death (22\% increase)
  \item Size of the original monoclonal has a large effect
    on PCM \\
    but almost no impact on death rates
\end{itemize}
\end{frame}

\begin{frame}{Progression to PCM}
<<mgus2d>>=
plot(mfit2[,1],  col=c(1,2), xmax=15*12, 
     mark.time=FALSE, lwd=2,  xscale=12,
     xlab="Years post diagnosis", ylab="Progression to PCM")
legend(96, .03, c("Female", "Male"), lty=1, col=1:2, lwd=2,
       bty='n')
@ 
\end{frame}

<<expect, echo=FALSE>>=
# mean years of life remaining, used in lines below, but not shown
efit1 <- survexp(~ sex, data=mgus2, times=365.25*(0:150)/2,
                 rmap=list(sex=sex, age=age*365.25, year=as.Date("1980-01-01")),
                 ratetable=survexp.mn)
lifeleft <- colSums(efit1$surv)/2  # area under the curve
@ 

\begin{frame}{Lesson 1}
  \begin{itemize}
    \item Any given rate (arrow) is modeled using that endpoint and
      ignoring all others (treat them as censored).  Individual rates
      are local.
    \item The probability of being in any one state (box) depends on \emph{all}
      the rates.  States are global.
      \begin{itemize}
        \item Sex has no effect on progression to PCM.
        \item But females have a higher 15 year risk (9.5 vs 7.5) \pause
        \item Mean life remaining for this age distribution is 
          \Sexpr{round(lifeleft[1],1)} and \Sexpr{round(lifeleft[2],1)},
          respectively.
      \end{itemize}
  \end{itemize}
\end{frame}

\begin{frame}
  \begin{itemize}
    \item Underlying biology question: does gender affect the rate of
      progression?
    \item Public health question: does gender affect the lifetime risk?
    \item They have different answers.
  \end{itemize}
\end{frame}

\begin{frame}
<<mgus3>>=
pcmbad <- survfit(Surv(etime, pstat) ~ sex, data=mgus2)
plot(pcmbad, lwd=2, fun="event", conf.int=FALSE,
     xscale=12, xmax=20*12, col=1:2, lty=2,
     xlab="Years after MGUS diagnosis", ylab="Fraction with PCM")
lines(mfit2[,1], lty=1, lwd=2, col=1:2)
legend(0, .18, c("PCM, incorrect curve", "PCM, competing risk"),
       col=1, lwd=2, lty=c(2,1), bty='n')
@ 
\end{frame}

<<echo=FALSE>>=
require("survival")
opts_chunk$set(comment=NA, tidy=FALSE, highlight=FALSE, echo=FALSE,
               fig.with=7, fig.height=5.5, fig.path="figures/",
               out.width="\\textwidth", out.height="!", device="pdf",
               cache=FALSE, background="#ffffff",
               warning=FALSE, error=FALSE, prompt=TRUE)
options(contrasts= c("contr.treatment", "contr.poly"),
        show.signif.starts = FALSE, continue=" ", width=60)
par(mar=c(4.1, 4.1, 1.1, 1.1))

state3 <- function(what, horizontal=TRUE, ...) {
    if (length(what) != 3) stop("Should be 3 states")
    connect <- matrix(c(0,0,0, 1,0,0, 1,1,0), 3,3,
                      dimnames=list(what, what))
    if (horizontal) statefig(1:2, connect, ...)
    else statefig(matrix(1:2, ncol=1), connect, ...)
}
@ 

\begin{frame}
  \frametitle{Progression of MGUS}
  \begin{itemize}
    \item 1384 subjects with monoclonal gammopathy of undetermined significance
      (MGUS)
    \item R. Kyle, New Engl J Med 346:564-569 (2002)
    \item Questions
      \begin{itemize}
	\item Pattern of death and progression
	\item Relationship to age, sex, hemoglobin, creatinine, 
	  and amount of protein in the ``spike''
      \end{itemize}
  \end{itemize}
\end{frame}

\begin{frame}[fragile]
<<kyle1, echo=TRUE>>=
mgus2[1:5,]
@ 
\begin{itemize}
  \item Classic data set
    \begin{itemize}
      \item One row per subject
      \item Separate columns for death and plasma cell malignancy
      \item Follow-up continues after PCM
    \end{itemize}
\end{itemize}
\end{frame}

\begin{frame}[fragile]
  \frametitle{Common analysis}
<<kyle2, echo=FALSE>>=
kdeath <- survfit(Surv(futime, death) ~ sex, data=mgus2)
kprog  <- survfit(Surv(ptime, pstat) ~ sex, data=mgus2)
plot(kdeath, col=1:2, mark.time=FALSE, xscale=12, 
     xlab="Years")
lines(kprog, col=1:2, mark.time=FALSE, xscale=12, lty=2)
legend(132, .7, c("F", "M"), col=1:2, lty=1, bty='n')
@ 
\end{frame}

\begin{frame}[fragile]
<<kyle3, echo=TRUE, fig.show="hide">>=
etime <- with(mgus2, ifelse(pstat==0, futime, ptime))
event <- with(mgus2, ifelse(pstat==0, 2*death, 1))
event <- factor(event, 0:2, 
                labels=c("censor", "pcm", "death"))
table(event)

pfit <- survfit(Surv(etime, event) ~ sex, data=mgus2)
print(pfit)
plot(pfit)
@ 
\end{frame}

\begin{frame}[fragile]
<<kyle2c, echo=FALSE>>=   
plot(pfit, mark.time=FALSE, xscale=30.5,
     col=c(1,1,2,2), lty=c(1,2,1,2), lwd=2,
     ylab="prevalence", xlab="Years")
legend(150, .5, c("Death, F", "Death, M", "PCM, F", "PCM, M"),
      col=c(1,1,2,2), lty=c(2,1,2,1), lwd=2, bty='n')
@ 
\end{frame}


\begin{frame}{Competing Risks}
  \begin{itemize}
    \item For this model we are only interested in the first event for each
      subject.
    \item Formally we are treating progression to a plasma cell malignancy (PCM)
      as an \emph{absorbing state}, i.e., one 
      that subjects never exit. 
      \pause
      
    \item The event variable was created as a \emph{factor}.
      The first level of the factor must be censoring, which is the status code
      for those whose follow-up terminated without reaching either endpoint.
      Codes for the remaining states can be in any order. The labels are
      arbitrary.
    \item A simple print of the \code{pfit} object shows the order in
      which the curves will be displayed.  This information was used to 
      choose the line types and colors for the curves.
    \item Curves start at 0.
  \end{itemize}
\end{frame}

\begin{frame}[fragile]
  \frametitle{Tangle of yarn plot}
<<kyle4, echo=TRUE, fig.show="hide">>=
oldage <- (mgus2$age > 70)
bigm   <- mgus2$mspike > 1
pfit2 <- survfit(Surv(etime, event) ~ oldage + sex + 
                 bigm, data= mgus2)

plot(pfit2, col=rep(1:2, each=4), mark.time=FALSE,
     xscale=30.5)
@ 
\end{frame}

\begin{frame}
  \myfig{kyle4-1}
\end{frame}

\begin{frame}{subsets}
  \begin{itemize}
    \item For multi-state models arrangement, colors, and line types of the
      curves can be more time consuming than creating them
      \begin{itemize}
        \item Easy to plot a subset
      \end{itemize}
    \item Use this to simplify the plots
  \end{itemize}
\end{frame}

\begin{frame}[fragile]
<<kyle5, echo=FALSE>>=
par(mfrow=c(1,2))
pfit3 <- survfit(Surv(etime, event) ~ oldage + sex, mgus2)
plot(pfit3[,2], col=c(1,2,1,2), lty=c(1,1,2,2), lwd=2,
     xscale=30.5, mark.time=FALSE,
     xlab="Years post diagnosis", ylab="Death")
legend(6*30.5, .35, c("M >70", "F > 70", "M <=70", "F <=70"),
        col=c(2,1,2,1), lty=c(2,2,1,1), lwd=2, bty='n', cex=.8)
plot(pfit3[,1], col=c(1,2,1,2), lty=c(1,1,2,2), lwd=2,
     xscale=30.5, mark.time=FALSE,
     xlab="Years post diagnosis", ylab="Progression")
@ 
\end{frame}

\begin{frame}[fragile]
<<kyle6, echo=FALSE>>=
par(mfrow=c(1,2))
plot(pfit3[1:2,], col=c(1,1,2,2), lty=c(2,1,2,1), lwd=2,
     xscale=30.5, mark.time=FALSE,
     xlab="Years post diagnosis", ylab="P(state), age <=70")
legend(0, .85, c("M death", "F death", "M PCM", "F PCM"),
        col=c(2,1,2,1), lty=c(1,1,2,2), lwd=2, bty='n', cex=.8)
plot(pfit3[3:4,],  col=c(1,1,2,2), lty=c(2,1,2,1), lwd=2,
     xscale=30.5, mark.time=FALSE,
     xlab="Years post diagnosis", ylab="P(state), age >70")
par(mfrow= c(1,1))
@ 
\end{frame}

%\begin{frame}
%  \myfig{box2}
%\end{frame}

\begin{frame}{Multistate models}
  For multi-state data we normally use a (start, stop] data set.
\vspace{.2in}

$$
\begin{tabular}{ccccccc}
  id & time1 & time2 & status & sex & age&  systolic \\
  21 &  0    &    15 &    0   &  F &  25 &  117 \\
  21 & 15    &    45 &    1   &  F &  25 &  135 \\
  40 &  6    &    68 &    1   &  M &  48 &  144 \\
  \vdots
\end{tabular}
$$
\begin{itemize}
  \item time1, time2: over the interval (time1, time2]
  \item sex, age, systolic: covariates
  \item status: did the interval end in an event?
  \item tracks each subject through time 
    \pause
  \item often the starting point for further data sets
\end{itemize}
\end{frame}

\begin{frame}
  \begin{itemize}
    \item Easy (but boring) to build
    \item Easy to build it wrong  -- read the results!
    \begin{itemize}
      \item During any time that the subject is at risk, there is
        an interval in the data containing them
      \item No more than 1 copy of the subject at any given time (per strata)
    \end{itemize}
  \end{itemize}
\end{frame}

\begin{frame}
<<mgus3b>>=
state3(c("MGUS", "PCM", "Death"))
@ 
\begin{tabular}{cccccccc}
  id & age& sex & hgb& ptime & pstat & futime & death\\ \hline
 55 & 82 &  F& 11.0  &   94 &    0 &    94 &    1\\
 56 & 78 &  M &10.3   &  29  &   1  &   44  &   1\\
 57 & 79 &  F& 13.6 &    84 &    0  &   84  &   1
 \end{tabular}
\end{frame}

\begin{frame}
  \begin{itemize}
    \item 9 subjects have PCM and death declared at the same time.
    \item Treated as PCM in the CR analysis
    \item For the multi-state model we need to be explicit
    \item Push progressions back by .1 month when there is a tie
      \pause
    \item Many data sets have case like this.
  \end{itemize}
\end{frame}

\begin{frame}[fragile]
<<mgus4, echo=TRUE>>=
ptemp <- with(mgus2, ifelse(ptime==futime & pstat==1, ptime-.1, ptime))
mgus3 <- tmerge(mgus2, mgus2,  id=id, death=event(futime, death),
                  pcm = event(ptemp, pstat))
mgus3 <- tmerge(mgus3, mgus3, id, enum=cumtdc(tstart))
mgus3$event <- factor(mgus3$pcm + 2*mgus3$death, 0:2, 
                      c("censor", "PCM", "death"))
with(mgus3, table(death, pcm))
@ 
The table above shows that there are no observations in \code{mgus3}
that have both a PCM and death, i.e., the ties have been resolved.
The last \code{tmerge} line above creates a variable \code{enum} which
simply counts rows for each person; it will be used later.
\end{frame}

\begin{frame}
<<kyle9c, echo=FALSE>>=  
pfit3 <- survfit(Surv(tstart, tstop, event) ~ sex, 
                 data= mgus3, id=id)
oldpar <- par(mar=c(5.1, 4.1, 1.1, .1))
layout(matrix(c(1,1,2,3), 2,2), widths=2:1)

plot(pfit3, mark.time=FALSE, lwd=2, col=c(1,2,1,2),
     lty=c(1,1,2,2), xscale=30.5,
     xlab="Years post diagnosis", ylab="P(state)")

legend(6*30.5 , .5, c("M death", "F death", "M alive with PCM",
                "F alive with PCM"), col=c(1,2,1,2), 
       lty=c(2,2,1,1), bty='n')
par(mar=c(4, .1, 1, 1))
state3(c("Entry", "PCM", "Death"))

par(oldpar)
@        
\end{frame}

\begin{frame}[fragile]
<<kyle10, echo=FALSE>>=
plot(pfit3[,1], mark.time=FALSE, lwd=2, col=1:2,
     xscale=30.5, xlab="Years post diagnosis", ylab="Alive with PCM")
@ 
\end{frame}


\begin{frame}{Warnings}
  Whenever the data/fit can have multiple transitions for one person
  \begin{itemize}
    \item Remember the \code{id} statement
    \item The program has no way of knowing which rows go together without it,
      and instead will assume subjects have delayed entry
    \item A correct answer to the wrong question.  (Variance too).
  \end{itemize}
\end{frame}

\begin{frame}
  \begin{itemize}
    \item Individuals cannot have a ``hole'' in their follow-up time.
    \item Example: panel data
      \begin{itemize}
        \item Smith enters state 1 at one year
        \item The next time we see him, one year later, he is in state 3
          but we don't know when he made the transition.
        \item msm package
      \end{itemize}
    \item Example: gaps in follow-up
  \end{itemize}
\end{frame}
  
% Further work with fits
\begin{frame}{Cause specific rate models}
  \begin{itemize}
    \item Fit a separate model for each rate (arrow)
    \item Questions
      \begin{itemize}
        \item Which covariates for each rate?
        \item Standard Cox model stuff (PH, outliers, linearity, \ldots)
         \end{itemize}
      \pause
    \item Data
      \begin{itemize}
        \item Each model involves only those at risk for the rate =
          members of the box at the foot of the arrow.
        \item Those who leave, for whatever reason, are censored.
        \item The only events of interest are moves along this arrow.
      \end{itemize}
  \end{itemize}
\end{frame}

\begin{frame}[fragile]
<<mfit3, echo=TRUE>>=
cfit1 <- coxph(Surv(etime, event=="pcm") ~ age + sex+ mspike, 
               data= mgus2)
temp <- summary(cfit1, scale=c(10,1,1))
round(temp$conf.int, 2) 
#
cfit2 <- coxph(Surv(etime, event=="death") ~ age + sex+ mspike, 
               data= mgus2)
temp <- summary(cfit2, scale=c(10,1,1))
round(temp$conf.int, 2) 
@       
\end{frame}

\begin{frame}[fragile]
  \frametitle{Consequences of the rates}
  \begin{itemize}
    \item Can we predict multivariate outcome from a set of Cox models? Yes.
    \begin{itemize}
      \item As with all Cox models, prediction must be
        for some particular person(s).
      \item Decision: male/female by age 60/80, with mspike= 1.2
      \item Create a 4 observation data set \code{newdata}
       \pause
     \item Individual curves, from each Cox model alone, are useless;
          proper curves require \emph{all} the rates.
     \item Aalen-Johansen estimator, with $\lambda(t | z)$ as entries.
       \item Result is 8 curves: predicted lifetime risk of PCM and of
         death before PCM, each for m/f x diagnosis at age 60/80.
    \end{itemize}
  \end{itemize} 
\end{frame}

\begin{frame}
\begin{align*}
  H&= \left( \begin{array}{ccc}
     \lambda_{11}(t) & \lambda_{12}(t) &\lambda_{13}(t)  \\
     \lambda_{21}(t) & \lambda_{22}(t) &\lambda_{23}(t)  \\
     \lambda_{31}(t) & \lambda_{32}(t) &\lambda_{33}(t)  \\
       \end{array} \right) \\
  &= \left( \begin{array}{ccc}
       * & \lambda_{12}(t) &\lambda_{13}(t)  \\
       0 &  *  & 0  \\
       0 &  0 &  *  \\
       \end{array} \right) \\
  \end{align*}
\end{frame}

\begin{frame}
<<mfit4, echo=FALSE>>=
newdata <- expand.grid(sex=c("F", "M"), age=c(60, 80), mspike=1.2)

temp <- matrix(list(), 3,3)
temp[1,2] <- list(survfit(cfit1, newdata, std.err=FALSE))
temp[1,3] <- list(survfit(cfit2, newdata, std.err=FALSE))
csurv  <- survfit(temp, p0 =c(entry=1, PCM=0, death=0))
plot(csurv[,2], xmax=25*12, xscale=12, 
     xlab="Years after MGUS diagnosis", ylab="PCM",
     col=1:2, lty=c(1,1,2,2), lwd=2)
abline(0, .01/12, col=4, lty=3)
legend(10, .14, outer(c("female", "male   "), 
                     c("diagnosis at age 60", "diagnosis at age 80"), 
                      paste, sep=", "),
       col=1:2, lty=c(1,1,2,2), bty='n', lwd=2)
@ 
\end{frame}

\begin{frame}{Prediction at 25 years}
\begin{center} \begin{tabular}{cccc}
    & female & male& delta \\ \hline
   diagnosis at age 60 & .142 & .118 & .024\\
   diagnosis at age 80 & .086 & .060 & .026 
   \end{tabular} \end{center}

\begin{itemize}
  \item 2\% increase for females
  \item Not a constant wrt to other covariates, even though the 
    HR for sex is constant within each each of death and PCM.\\
    PH for components $\ne$ PH for the composite.
  \item A good summary is a population average prediction = mean prediction
    over the all the other covariates.
  \item Currently that is some busy work, standard error is hard though.
  \item Mean time in state is an alternative, but odd.
\end{itemize}
\end{frame}

\begin{frame}
<<mstate3>>=
par(mfrow=c(1,2))
crisk(c("MGUS", "PCM", "Death"))
state3(c("MGUS", "PCM", "Death"))
par(mfrow=c(1,1))
@ 
\end{frame}

% leave this out of the slides
%\begin{frame}[fragile]
%<<stime, echo=FALSE>>=
%newdata
%print(csurv[,2], rmean=25*12)
%@ 

%\begin{itemize}
%  \item 23.6 vs 20.9 (2.7 months) for 60 year olds
%  \item 18.4 vs 14.0 (4.4 months) for 80 year olds
%  \item Absolute effect is small; few 
%\end{frame}

\begin{frame}
<<mfit5>>=
plot(csurv[,3], xmax=25*12, xscale=12, 
     xlab="Years after MGUS diagnosis", ylab="Death before PCM",
     col=1:2, lty=c(1,1,2,2), lwd=2)
legend(110, .25, outer(c("female", "male   "), 
                     c("diagnosis at age 60", "diagnosis at age 80"), 
                      paste, sep=", "),
       col=1:2, lty=c(1,1,2,2), bty='n', lwd=2)
@ 
\end{frame}

\begin{frame}{mstate package}
  \begin{itemize}
    \item Issue: separate Cox models for each transition, 
      all are used to create the curves
    \item survival package: glue them together by hand
    \item mstate:
      \begin{itemize}
        \item create a marked up data set (add a transition matrix)
        \item fit the Cox models all at once
        \item curves use the resulting \code{mstate} object
      \end{itemize}
  \end{itemize}
\end{frame}

